---
galaxy_info:
  author: Red Hat GPTE
  description: MCP user provisioner for OCP Sandbox model (single user)
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
  - name: GenericLinux
    versions:
    - all
  galaxy_tags:
  - openshift
  - mcp
  - sandbox
dependencies: []
